# Generated by Django 5.2 on 2025-04-18 11:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_foodtruck_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('lunch', models.BooleanField(default=False)),
                ('dinner', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('food_truck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='core.foodtruck')),
            ],
            options={
                'db_table': 'food_schedules',
                'unique_together': {('food_truck', 'date')},
            },
        ),
    ]
