# Generated by Django 5.0.2 on 2025-04-23 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_foodschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtruck',
            old_name='type',
            new_name='truck_type',
        ),
    ]
